context:
  version: "1.2.0"

package:
  name: uuid
  version: ${{ version }}

source:
  - git: https://github.com/lczerniawski/uuid.git
    rev: 58f8e17e5111918195ceadd7d87dbe031eb4ba9f

build:
  number: 0
  script:
    - mojo precompile src/uuid -o ${{ PREFIX }}/lib/mojo/uuid.mojoc

requirements:
  build:
    - mojo-compiler =1.0.0
    - crypto =0.2.0
  host:
    - mojo-compiler =1.0.0
    - crypto =0.2.0
  run:
    - ${{ pin_compatible('mojo-compiler') }}
    - ${{ pin_compatible('crypto') }}

tests:
  - script:
      - if: unix
        then:
          - mojo run test.mojo
    files:
      recipe:
        - test.mojo

about:
  homepage: https://github.com/lczerniawski/uuid
  repository: https://github.com/lczerniawski/uuid
  license: MIT
  license_file: LICENSE
  summary: A high-performance Mojo library for generating, parsing, validating, and formatting UUID values in RFC-9562 compatible string forms.

extra:
  maintainers:
    - lczerniawski
