context:
  version: "0.2.0"
  mojo_version: "=1.0.0"

package:
  name: mojo-intel-gpu
  version: ${{ version }}

source:
  - git: https://github.com/andomeder/mojo-intel-gpu.git
    rev: d3936acd5b3802e622b5f222982af57c8a0515f3

build:
  number: 0
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - mojo precompile mojo_intel_gpu -o ${PREFIX}/lib/mojo/mojo_intel_gpu.mojoc

requirements:
  host:
    - mojo-compiler ${{ mojo_version }}
  build:
    - mojo-compiler ${{ mojo_version }}
  run:
    - mojo-compiler ${{ mojo_version }}

about:
  homepage: https://github.com/andomeder/mojo-intel-gpu
  repository: https://github.com/andomeder/mojo-intel-gpu
  license: MIT
  license_file: LICENSE
  summary: Level Zero FFI bindings and high-level API for Intel GPU compute in Mojo

extra:
  project_name: mojo-intel-gpu
  maintainers:
    - andomeder
