context:
  version: "0.2.0"

package:
  name: crypto
  version: ${{ version }}

source:
  - git: https://github.com/lczerniawski/crypto.git
    rev: 86b28833b85cbfa050df8eb8b582958cbf6b6f6f

build:
  number: 0
  script:
    - mojo precompile src/crypto -o ${{ PREFIX }}/lib/mojo/crypto.mojoc

requirements:
  build:
    - mojo-compiler =1.0.0
  host:
    - mojo-compiler =1.0.0
  run:
    - ${{ pin_compatible('mojo-compiler') }}

tests:
  - script:
      - if: unix
        then:
          - mojo run test.mojo
    files:
      recipe:
        - test.mojo

about:
  homepage: https://github.com/lczerniawski/crypto
  repository: https://github.com/lczerniawski/crypto
  license: MIT
  license_file: LICENSE
  summary: A Mojo cryptography library intended to cover the commonly used cryptographic algorithms.

extra:
  maintainers:
    - lczerniawski
