name: Remove Incompatible Packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *" # 9 AM PST

permissions:
  contents: write
  pull-requests: write

jobs:
  check-incompatible-packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2
      - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          pixi-version: v0.63.2

      - name: Configure git
        run: pixi run configure-git

      - name: Run compatibility check script
        run: pixi run remove-incompatible-packages
        env:
          GITHUB_REPOSITORY: "${{ github.repository }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
